### ISSUE TITLE
Is missing icons

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.artemanufrij.playmymusic#1]
![captura de tela de 2018-09-02 17-52-16](https://user-images.githubusercontent.com/26097419/44960621-43987000-aed9-11e8-994c-1b3705315735.png)

**Comment by bilelmoussaoui** [comment]
Oh that's something interesting! I'm going to add elementary icons by default on the elementary loki BaseApp so other elementary packages can use the default elementary icons to lopk the most the way the dev wanted it to be. Then, I'm going to patch the package to force elementary icons theme(just for the application of course).
@artemanufrij What do you think?

**Comment by artemanufrij** [comment]
@bilelmoussaoui It would be very helpful. So it wouldn't be necessary to ship all icons the app needs separate in each project.

**Comment by bilelmoussaoui** [comment]
Fixed on master.

**Comment by bilelmoussaoui** [comment]
Should be there on the next update
