### ISSUE TITLE
New release available

### ISSUE THREAD

**Issue by artemanufrij** [flathub/com.github.artemanufrij.playmymusic#5]
Hey @bilelmoussaoui, how can I release a new version for flatpak?

**Comment by bilelmoussaoui** [comment]
If the new release doesn't add any new dependencies you just need to modify those two lines
https://github.com/flathub/com.github.artemanufrij.playmymusic/blob/master/com.github.artemanufrij.playmymusic.json#L92-L93
with the tarball link & sha256sum of it. You need to push that into a new branch and a create a PR. Once the PR is created you can test if everything builds correctly using `bot, build` (write that in a comment). You can see the status of the build in https://flathub.org/status. If the build was okay, you can merge it. That's all.
Ping me if you need any help
