### ISSUE TITLE
add --filesystem=xdg-music

### ISSUE THREAD

**Issue by muadib** [flathub/com.github.artemanufrij.playmymusic#8]
Hi!
I use an external drive for my music, and had create a link in /home/user/Music.
Is valid to add `--filesystem=xdg-music` in `finish-args`?
Thanks

**Comment by TingPing** [comment]
I'd probably argue that should be the only filesystem permission by default. If @artemanufrij 	wants to keep full permissions then it should change `home` to `host`.

**Comment by artemanufrij** [comment]
Hey guys, I agree. Could you open a PR, please?

**Comment by bilelmoussaoui** [comment]
I have changed the filesystem from home to host.
